### ISSUE TITLE
solvePnP only takes 6 points, but MTCNN has 5 points. How was this issue addressed?

### ISSUE THREAD

**Issue by vvenkatesh-ML** [JuneoXIE/mtcnn-opencv_face_pose_estimation#1]

**Comment by sogris** [comment]
What was the solution for this problem please?

**Comment by vvenkatesh-ML** [comment]
I did not receive a solution, but I was able to do a work around by taking another point at the nose which is the center point. So that would be 2 for eyes, 2 for lips, and 2 for nose. Making it a total of 6 which then meets the criteria for rotation matrix.

**Comment by sogris** [comment]
Ok thanks! I will try that.
